### ISSUE TITLE
Header inconsistency of LM imaging simulation

### ISSUE THREAD

**Issue by chyan26** [AstarVienna/METIS_Simulations#103]
I used lmg.yaml to run a set of simulation data with following setting
```
LM_IMAGE_SCI_RAW1:
  do.catg: LM_IMAGE_SCI_RAW
  mode: "img_lm"
  source:
    name: star_field
    kwargs: {}
  properties:
    dit: 0.25
    ndit: 4
    filter_name: "Lp"
    catg: "SCIENCE"
    tech: "IMAGE,LM"
    type: "OBJECT"
    tplname: "METIS_img_lm_obs_GenericOffset"
    nObs: 3

LM_IMAGE_SCI_RAW2:
  do.catg: LM_IMAGE_SKY_RAW
  mode: "img_lm"
  source:
    name: "empty_sky"
    kwargs: {}
  properties:
    dit: 0.25
    ndit: 4
    filter_name: "Lp"
    catg: "SCIENCE"
    tech: "IMAGE,LM"
    type: "SKY"
    tplname: "METIS_img_lm_obs_GenericOffset"
    nObs: 3
```

However, the FITS header `DPR CATG ` of the first frame of sky background is not the same as reset.  This caused problem for EDPS to pick the sky background image.
